# NUMPY ARRAYS


Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array 
object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.
It is open-source software.

->Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. '
->In Numpy, number of dimensions of the array is called rank of the array.
->A tuple of integers giving the size of the array along each dimension is known as shape of the array. 
->An array class in Numpy is called as ndarray.

Numpy arrays vs list
Unlike lists, NumPy arrays are of fixed size, and changing the size of an array will lead to the creation of a 
new array while the original array will be deleted.
All the elements in an array are of the same type.
Numpy arrays are faster, more efficient, and require less syntax than standard python sequences.

In [2]:
import numpy as np
list=[1,2,3,4]
arr=np.array(list)
print(arr)

[1 2 3 4]


In [1]:
import array
arr=array.array('i',[1,2,3])
print("The new created array is: ", end="")
for i in range(0,3):
    print(arr[i],end=" ")

The new created array is: 1 2 3 

In [3]:
type(arr)

numpy.ndarray

In [2]:
#numpy.empty(shape, dtype = float, order = ‘C’)
import numpy as np
a=np.empty(2,dtype=int)
print("Matrix a : \n", a)

b = np.empty([2, 2], dtype = int)
print("\nMatrix b : \n", b)
 
c = np.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix a : 
 [1065353216 1065353216]

Matrix b : 
 [[  592743213 -1820210279]
 [-1548596799   768568353]]

Matrix c : 
 [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 4.64421707e-321]
 [1.42810317e-311 2.00485144e-307 0.00000000e+000]]


In [4]:
import numpy as np
list1=[1,2,3]
list2=[4,5,6]
arr2=np.array([list1,list2])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
print(arr2.shape)

(2, 3)


In [9]:
import numpy as np
arr1=np.array([[0,4,2]])
arr2=np.array([0.2,0.4,2.4])
print(arr1.dtype)
print(arr2.dtype)

int32
float64


In [10]:
#syntax: numpy.array(parameter)
import numpy as np
arr=np.array([3,5,4,2])
print(arr)

[3 5 4 2]


In [17]:
import numpy as np
iterable=(a*a for a in range(8))
arr=np.fromiter(iterable,int)
iterable=(b+b for b in range(4))
brr=np.fromiter(iterable,float)
print(arr)
print(brr)

[ 0  1  4  9 16 25 36 49]
[0. 2. 4. 6.]


In [18]:
import numpy as np
str = "Geekforgeeks"
arr = np.fromiter(str, dtype = 'U2')
print(arr)

['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


In [22]:
#numpy.arange([start, ]stop, [step,]dtype=None)
import numpy as np
np.arange(1, 20 , 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
#numpy.empty(shape, dtype=int, order='C')
import numpy as np
np.empty([4, 3],dtype = np.int32,order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
#numpy.ones(shape, dtype=int, order='C')
import numpy as np
 
np.ones([4, 3],dtype = np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [3]:
import numpy as np
arr=np.zeros([4, 3],dtype = np.int32)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [1]:
import numpy as np
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [8]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]],dtype='float')#array created using lists
print(a)
b=np.array((1,3,4)) #arrays using tuple
print(b)
c=np.zeros((3,4),dtype='int')
print(c)
d=np.full((3,3),6,dtype='complex')#array initialised with all 6's
print(d)
e=np.random.random((2,2))#create array using random values
print(e)
f=np.arange(0,30,5) #create array from sequence 
print(f)
g=np.linspace(0,5,10)# Create a sequence of 10 values in range 0 to 5
print(g)

[[1. 2. 4.]
 [5. 8. 7.]]
[1 3 4]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
[[0.48399124 0.53704626]
 [0.63683544 0.2761012 ]]
[ 0  5 10 15 20 25]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [15]:
#reshaping array : 3X4 array to 2X2X3 array
arr=np.array([[1,2,3,4],
              [5,2,4,7],
              [1,2,0,1]])
newarr=arr.reshape(2,2,3)
print("original array :\n",arr)
print("reshaped array :\n",newarr)

original array :
 [[1 2 3 4]
 [5 2 4 7]
 [1 2 0 1]]
reshaped array :
 [[[1 2 3]
  [4 5 2]]

 [[4 7 1]
  [2 0 1]]]


In [16]:
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
 
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


In [86]:
n1=np.random.randint(10,size=(3,2))
n1.ravel() 
#Ravel function flattens the array (i.e. convert to a 1-dimensional array).

array([6, 8, 1, 8, 4, 1])

In [19]:
import numpy as np
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])

temp=arr[:2,::2] #Array with first 2 rows and alternate columns(0 and 2)
print(temp)

temp=arr[[0,1,2,3],[3,2,1,0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)

cond=(arr%2==0)
temp=arr[cond]
print("\n Elements even : \n",temp)
 

[[1 3]
 [5 7]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [ 4  7 10 13]

 Elements even : 
 [ 2  4  6  8 10 12 14 16]


In [20]:
#ARITHMETIC OPERATORS
import numpy as np
a = np.array([1, 2, 5, 3])

print ("Adding 1 to every element:", a+1)

print ("Subtracting 3 from each element:", a-3)

print ("Multiplying each element by 10:", a*10)

print ("Squaring each element:", a**2)

a *= 2
print ("Doubled each element of original array:", a)
 
# transpose of array : arr.T
arr = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
 
print ("\nOriginal array:\n", arr)
print ("Transpose of array:\n", arr.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [27]:
#UNARY OPERATORS
import numpy as np
arr=np.array([[1,5,6],[4,7,2],[3,1,9]])

#maximum element of array
print("Largest element is:",arr.max())
print("Row wise max elements:", arr.max(axis=1))
print("Column wise max elements:", arr.max(axis=0))

# minimum element of array
print ("Column-wise minimum elements:",arr.min(axis = 0))

# sum of array elements
print ("Sum of all array elements:",arr.sum())
print("Row wise sum of elements: ",arr.sum(axis=1))

# cumulative sum along each row
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Largest element is: 9
Row wise max elements: [6 7 9]
Column wise max elements: [4 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Row wise sum of elements:  [12 13 13]
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [28]:
#BINARY OPERATORS
import numpy as np
a=np.array([[1,2],
            [3,4]])
b=np.array([[4,3],
           [2,1]])

#add two arrays
print("Array sum:\n",a+b)

print("array multiplication: \n",a*b)

#matrix multiplication
print("matrix multiplication:\n",a.dot(b))


Array sum:
 [[5 5]
 [5 5]]
array multiplication: 
 [[4 6]
 [6 4]]
matrix multiplication:
 [[ 8  5]
 [20 13]]


In [29]:
#universal functions
import numpy as np

# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
 
# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
 
# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [31]:
#SORTING ARRAY
import numpy as np
a=np.array([[1,4,2],
            [3,4,6],
            [0,-1,5]])

print("sorted array :\n",np.sort(a,axis=None))
print("Row wise sorted array:\n",np.sort(a,axis=1))

# specify sort algorithm
print ("Column wise merge-sort:\n",np.sort(a, axis = 0, kind = 'mergesort'))


sorted array :
 [-1  0  1  2  3  4  4  5  6]
Row wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [35]:
dtypes=[('name','S10'),('year',int),('cgpa',float)]
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
arr=np.array(values,dtype=dtypes)
print("Array sorted by names:\n",np.sort(arr,order='name'))

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]


In [37]:
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))

Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [38]:
list=[1,2,3,4]
arr=np.array(list)
print(arr)
print(type(arr))#arr is an array object of numpy
#note: array class in numpy is called ndarray

[1 2 3 4]
<class 'numpy.ndarray'>


In [39]:
tuple=(1,2,3,4)
arr=np.array(tuple)
#arr=np.array((1,2,3,4))
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [40]:
#COPY FUNCTION
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print("Before arr1", arr1)
print("Before arr2",arr2)
#np.copytp(destination,source)
np.copyto(arr1,arr2)
print("After arr1", arr1)
print("After arr2",arr2)

Before arr1 [1 2 3]
Before arr2 [4 5 6]
After arr1 [4 5 6]
After arr2 [4 5 6]


In [42]:
#WHERE
n=np.arange(15).reshape(5,3)
n[np.where(n>10)]
print(n)

array([11, 12, 13, 14])

In [44]:
ar = np.array([1,2,3,4,5,6,7,8,9])
np.put(ar,[1,2],[10,11])
print(ar)

[ 1 10 11  4  5  6  7  8  9]


In [46]:
#matrix multiplication
x1=([[1,2],[3,4]])
x2=([[5,6],[7,8]])
m=np.matmul(x1,x2)
print(m)

[[19 22]
 [43 50]]


In [47]:
#dot product
x1=np.array([1,2,3])
x2=np.array([3,2,8])
np.dot(x1,x2)

31

In [48]:
#linear algebra
n=np.array([[2,3],[4,1]])
#determinant of matrix
d=np.linalg.det(n)
print(d)

-10.000000000000002


In [49]:
#inverse of matrix
i=np.linalg.inv(n)
print(i)

[[-0.1  0.3]
 [ 0.4 -0.2]]


In [50]:
# eigenvalues and right eigenvectors for a square matrix.
e=np.linalg.eig(n)
print(e)

(array([ 5., -2.]), array([[ 0.70710678, -0.6       ],
       [ 0.70710678,  0.8       ]]))


In [54]:
#Vsplit: vertical split
n=np.random.randint(6,size=(4,3))
print(n)
x=np.vsplit(n,2)
x

[[4 3 3]
 [3 2 4]
 [4 5 1]
 [1 3 2]]


[array([[4, 3, 3],
        [3, 2, 4]]),
 array([[4, 5, 1],
        [1, 3, 2]])]

In [55]:
print(x[0])
print(x[1])

[[4 3 3]
 [3 2 4]]
[[4 5 1]
 [1 3 2]]


In [57]:
#hsplit: horizontal split
n=np.random.randint(6,size=(4,4))
print(n)
h=np.hsplit(n,2)
h

[[4 5 0 3]
 [0 4 5 4]
 [2 0 5 1]
 [0 2 3 2]]


[array([[4, 5],
        [0, 4],
        [2, 0],
        [0, 2]]),
 array([[0, 3],
        [5, 4],
        [5, 1],
        [3, 2]])]

In [58]:
#comparison
n1=np.array([10,20,30])
n2=np.array([10,30,20])
np.equal(n1,n2)


array([ True, False, False])

In [59]:
np.array_equal(n1,n2)

False

In [60]:
#vertical stack
n1=np.array([10,20,30])
n2=np.array([10,30,20])
np.vstack((n1,n2))

array([[10, 20, 30],
       [10, 30, 20]])

In [61]:
#horizontal stack
n1=np.array([10,20,30])
n2=np.array([10,30,20])
np.hstack((n1,n2))

array([10, 20, 30, 10, 30, 20])

In [62]:
#column stack
n1=np.array([10,20,30])
n2=np.array([40,60,50])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 60],
       [30, 50]])

In [63]:
#intersection
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.intersect1d(n1,n2)

array([50, 60])

In [64]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [65]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [70]:
n1=np.array([10,20])
n2=np.array([30,40])
print(np.sum([n1,n2]))
print(np.sum([n1,n2],axis=0)) #axis:0 row wise
#axis:1 column wise
np.sum([n1,n2],axis=1)

100
[40 60]


array([30, 70])

In [71]:
#concatenation row wise
mat1=np.array([[1,2,3],
               [4,5,6]])
mat2=np.array([[7, 8, 9],
               [10, 11, 12]])
x=np.concatenate([mat1,mat2],axis=0)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
#concatenation row wise
mat1=np.array([[1,2,3],
               [4,5,6]])
mat2=np.array([[7, 8, 9],
               [10, 11, 12]])
x=np.concatenate([mat1,mat2],axis=1)
x

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [73]:
np.random.randint(0,10,(3,3))

array([[1, 4, 9],
       [8, 0, 8],
       [0, 6, 1]])

In [74]:
np.random.randint(0,10,9)

array([2, 6, 2, 0, 5, 8, 9, 9, 1])

In [76]:
x=np.random.random(5)
print(x)

[0.33280734 0.97705435 0.1094375  0.54500119 0.4052356 ]


In [82]:
x=np.random.randn(10)
print(x)
m=x.mean()
print(m)
s=x.std()
print(s)

[ 2.79837211  0.67023346  0.93504352  0.46899457  1.35337894  1.29919027
  0.86152856 -0.23651554  0.25877092  0.13898101]
0.8547977827009449
0.8044593371744387


In [83]:
np.random.seed(0) #fixing the random seed
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [84]:
np.random.seed(10)
np.random.randint(0, 10, (3, 3))

array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9]])

In [85]:
n1=np.random.randint(1,100,5)
n1

array([ 1, 41, 37, 17, 12])

In [ ]:
import numpy as np

# Read dataset from CSV file
data = np.genfromtxt('data.csv', delimiter=',')

# Calculate mean for the first column
a = np.mean(data[:, 0])
print("Mean of first column:", a)

# Select every second element of the fifth row
b= data[4, ::2]
print("Every second element of the fifth row:", b)

# Values that are between 90 and 95
c = data[(data > 90) & (data < 95)]
print("Values between 90 and 95:", c)

# Sort values in descending order for each column
d= np.sort(data, axis=0)[::-1]
print("Sorted in descending order for each column:", d)

In [4]:
import numpy as np
arr=np.arange(8)
print(arr)

arr=np.arange(8).reshape(4,2)
print(arr)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [6]:
arr=np.arange(4,10)
print(arr)

arr1=np.arange(4,20,3).reshape(2,3)
print(arr1)

[4 5 6 7 8 9]
[[ 4  7 10]
 [13 16 19]]


In [7]:
#full and empty array
#numpy.full(shape,fill_value, dtype=None, order='C')
#numpy.empty(shape,dtype=float,order='C')
import numpy as np
arr=np.empty((3,4),dtype=int)
print("Empty array \n",arr)

arr2 = np.full([3, 3], 55, dtype=int)
print("\n Full Array \n")
print(arr2)


Empty array 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 Full Array 

[[55 55 55]
 [55 55 55]
 [55 55 55]]


In [9]:
#loading and saving data in numpy
import numpy as np
data=np.array([[1,2,3],[4,5,6]])

#save data to file
np.save('data.npy',data)

#load data from file
load_data=np.load('data.npy')

print(load_data)

[[1 2 3]
 [4 5 6]]


In [ ]:
If you want to save multiple arrays, you can use the np.savez() 
function instead of np.save(). This function allows you to save 
multiple arrays to a single compressed file. 

In [11]:
import numpy as np

# create some sample arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# save the arrays to a file
np.savez('data.npz', array1=array1, array2=array2)

# load the arrays from the file
loaded_data = np.load('data.npz')

# extract the arrays from the loaded data
loaded_array1 = loaded_data['array1']
loaded_array2 = loaded_data['array2']

# print the loaded arrays
print(loaded_array1)
print(loaded_array2)

[1 2 3]
[4 5 6]


In [13]:
#saving an array
import numpy as np
arr=np.array([1,2,3,4,5])

np.save('arr.npy',arr)

#Note that the np.save() function automatically adds a .npy extension 
#to the filename you provide. This is a binary format specific to NumPy 
#that allows for efficient reading and writing of large arrays.

In [14]:
loaded_array=np.load('arr.npy')
print(loaded_array)

#The np.load() function automatically detects the data type and shape of the
#saved array, so you don't need to specify these parameters explicitly. 

[1 2 3 4 5]


In [ ]:
#loading array from text file or another file format
import numpy as np
array=np.loadtxt('arr.txt',delimiter=',')
print(array)

In this example, we use the np.loadtxt() function to load an array from a 
text file called my_array.txt. We specify the delimiter as a comma , 
because the values in the text file are separated by commas. If your data 
is separated by a different delimiter like a space or tab, you can specify 
that instead.



In [ ]:
arr=np.loadtxt('array.txt',dtype=int,delimiter=' ')
print(arr)
By default, np.loadtxt() assumes that all values in the text file are floats,
but you can specify a different data type using the dtype parameter. 
For example, dtype=int would load the values as integers.

In [ ]:
The main difference between copy and view is that the copy is the new array
whereas the view is the view of the original array.
the copy is physically stored at another location and view has 
the same memory location as the original array.
#copy and view in numpy array

In [15]:
#Normal assignments do not make the copy of an array object. 
#Instead, it uses the exact same id of the original array to access it. 
arr=np.array([1,2,3])
copyarr=arr
print(id(arr))
print(id(copyarr))
copyarr[0]=4
print(arr)
print(copyarr)

2894340067472
2894340067472
[4 2 3]
[4 2 3]


In [ ]:
The view is just a view of the original array and view does not own the data.
When we make changes to the view it affects the original array, and 
when changes are made to the original array it affects the view.

In [17]:
ar=np.array([1,2,3])
v=ar.view()
print(id(ar))
print(id(v))
ar[0]=7
print(ar)
print(v)

2894340067664
2894340068624
[7 2 3]
[7 2 3]


In [ ]:
Copy: This is also known as Deep Copy. The copy is completely a new array 
    and copy owns the data. When we make changes to the copy it does not 
    affect the original array, and when changes are made to the original
    array it does not affect the copy.

In [18]:
a=np.array([1,2,3])
c=a.copy()
print(id(a))
print(id(c))
a[0]=12
print(a)
print(c)

2894339886416
2894318035280
[12  2  3]
[1 2 3]


In [19]:
#copying array
arr=np.array([3,4,5,7])
print(arr)
copy=np.empty_like(arr) #creating an empty array
copy[:]=arr
print(copy)

[3 4 5 7]
[3 4 5 7]


In [20]:
import numpy as np
arr=np.array([3,4,8,9,7])
print(arr)
c=np.copy(arr)
print(c)

[3 4 8 9 7]
[3 4 8 9 7]


In [21]:
#appending values at end of array
import numpy as np
arr = np.array([1, 8, 3, 3, 5])
print(arr)
arr = np.append(arr, [7])
print(arr)

[1 8 3 3 5]
[1 8 3 3 5 7]


In [22]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.append(arr1,arr2)
print(arr)

[1 2 3 4 5 6]


In [26]:
import numpy as np
arr=np.arange(1,13).reshape(2,6)
print(arr)

#appending array column wise
col=np.arange(5,11).reshape(1,6)
print(col)
arr1=np.append(arr,col,axis=0)
print(arr1)

#appending array row wise
row=np.array([1,2]).reshape(2,1)
print(row)
arr2=np.append(arr,row,axis=1)
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 5  6  7  8  9 10]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]]
[[1]
 [2]]
[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


In [27]:
#swapping columns in numpy array
arr=np.arange(12).reshape(4,3)
print(arr)

arr[:,[2,0]]=arr[:,[0,2]]
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


In [ ]:
numpy.hstack() function is used to stack the sequence of 
input arrays horizontally (i.e. column wise) to make a single array.
Syntax : numpy.hstack(tup)

Parameters :
tup : [sequence of ndarrays] Tuple containing arrays to be stacked. 
The arrays must have the same shape along all but the second axis.

In [29]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
arr=np.hstack((a1,a2))
print(arr)

[1 2 3 4 5 6]


In [31]:
a1=np.array([[1,2,3],[5,8,7]])
a2=np.array([[4,5,6],[6,9,7]])
arr=np.hstack((a1,a2))
print(arr)

[[1 2 3 4 5 6]
 [5 8 7 6 9 7]]


In [ ]:
numpy.vstack() function is used to stack the sequence of input arrays
vertically to make a single array.
Syntax : numpy.vstack(tup)

Parameters :
tup : [sequence of ndarrays] Tuple containing arrays to be stacked. 
The arrays must have the same shape along all but the first axis.

In [32]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
arr=np.vstack((a1,a2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [33]:
a1=np.array([[1,2,3],[5,8,7]])
a2=np.array([[4,5,6],[6,9,7]])
arr=np.vstack((a1,a2))
print(arr)

[[1 2 3]
 [5 8 7]
 [4 5 6]
 [6 9 7]]


In [34]:
#combining arrays
a1=np.array([1,2,3])
a2=np.array([4,5,6])
arr_new=np.concatenate((a1,a2))
print(arr_new)

#by default value of axis is 0

[1 2 3 4 5 6]


In [37]:
#combining arrays
a1=np.array([[1,2,3],[4,9,7]])
a2=np.array([[4,5,6],[3,5,4]])
arr_new=np.concatenate((a1,a2),axis=1)
print(arr_new)

arr_2=np.concatenate((a1,a2))
print(arr_2)

#by default value of axis is 0

[[1 2 3 4 5 6]
 [4 9 7 3 5 4]]
[[1 2 3]
 [4 9 7]
 [4 5 6]
 [3 5 4]]


In [38]:
a1=np.array([[1,2,3],[4,9,7]])
a2=np.array([[4,5,6],[3,5,4]])
arr_new=np.stack((a1,a2),axis=1)
print(arr_new)

[[[1 2 3]
  [4 5 6]]

 [[4 9 7]
  [3 5 4]]]


In [39]:
import numpy as np
  
block_1 = np.array([[1, 1], [1, 1]])
block_2 = np.array([[2, 2, 2], [2, 2, 2]])
block_3 = np.array([[3, 3], [3, 3], [3, 3]])
block_4 = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]])
  
block_new = np.block([
    [block_1, block_2],
    [block_4, block_3]
])
  
print(block_new)

[[1 1 2 2 2]
 [1 1 2 2 2]
 [4 4 4 3 3]
 [4 4 4 3 3]
 [4 4 4 3 3]]


In [1]:
import numpy as np
  
gfg1 = np.array([1, 2, 3])
gfg2 = np.array([4, 5, 6])

print(np.dstack((gfg1, gfg2)))

[[[1 4]
  [2 5]
  [3 6]]]
